// Copyright (c) Heribert Gasparoli Private. All rights reserved.

/// <summary>
/// Verifies that the three mail threading columns added to received_emails (in_reply_to,
/// thread_references, is_auto_generated) exist in the real schema and round-trip. Rows are scoped by
/// the INTEGRATION_TEST_ prefix on MessageId.
/// </summary>

using Klacks.Api.Domain.Models.Email;
using Klacks.Api.Infrastructure.Persistence;
using Microsoft.AspNetCore.Http;
using Microsoft.EntityFrameworkCore;
using NSubstitute;
using NUnit.Framework;
using Shouldly;

namespace Klacks.IntegrationTest.Inbound;

[TestFixture]
[Category("RealDatabase")]
public class ReceivedEmailThreadHeaderPersistenceTests
{
    private const string TestPrefix = "INTEGRATION_TEST_THREAD_";
    private const string DefaultConnectionString = "Host=localhost;Port=5434;Database=klacks;Username=postgres;Password=admin";

    private DataBaseContext _context = null!;

    [SetUp]
    public void SetUp()
    {
        var connectionString = Environment.GetEnvironmentVariable("DATABASE_URL") ?? DefaultConnectionString;
        var options = new DbContextOptionsBuilder<DataBaseContext>()
            .UseNpgsql(connectionString)
            .UseSnakeCaseNamingConvention()
            .Options;
        _context = new DataBaseContext(options, Substitute.For<IHttpContextAccessor>());
    }

    [TearDown]
    public async Task TearDown()
    {
        await _context.ReceivedEmails.IgnoreQueryFilters()
            .Where(e => e.MessageId.StartsWith(TestPrefix))
            .ExecuteDeleteAsync();
        await _context.DisposeAsync();
    }

    [Test]
    public async Task ThreadHeaderColumns_RoundTrip()
    {
        var email = new ReceivedEmail
        {
            Id = Guid.NewGuid(),
            MessageId = TestPrefix + Guid.NewGuid().ToString("N") + "@example.com",
            Folder = "INBOX",
            SourceImapFolder = "INBOX",
            FromAddress = "anna@example.com",
            ToAddress = "klacks@example.com",
            Subject = "Re: Rückfrage",
            ReceivedDate = DateTime.UtcNow,
            InReplyTo = "question-1@klacks.example",
            ThreadReferences = "original-1@example.com question-1@klacks.example",
            IsAutoGenerated = true
        };
        _context.ReceivedEmails.Add(email);
        await _context.SaveChangesAsync();
        _context.ChangeTracker.Clear();

        var reread = await _context.ReceivedEmails.AsNoTracking().SingleAsync(e => e.Id == email.Id);

        reread.InReplyTo.ShouldBe("question-1@klacks.example");
        reread.ThreadReferences.ShouldBe("original-1@example.com question-1@klacks.example");
        reread.IsAutoGenerated.ShouldBeTrue();
    }

    [Test]
    public async Task InReplyTo_LongerThan998Characters_RoundTrips()
    {
        var oversizedInReplyTo = "oversized-" + new string('a', 1500) + "@example.com";
        var email = new ReceivedEmail
        {
            Id = Guid.NewGuid(),
            MessageId = TestPrefix + Guid.NewGuid().ToString("N") + "@example.com",
            Folder = "INBOX",
            SourceImapFolder = "INBOX",
            FromAddress = "anna@example.com",
            ToAddress = "klacks@example.com",
            Subject = "Re: Rückfrage",
            ReceivedDate = DateTime.UtcNow,
            InReplyTo = oversizedInReplyTo
        };
        _context.ReceivedEmails.Add(email);
        await _context.SaveChangesAsync();
        _context.ChangeTracker.Clear();

        var reread = await _context.ReceivedEmails.AsNoTracking().SingleAsync(e => e.Id == email.Id);

        reread.InReplyTo.ShouldBe(oversizedInReplyTo);
    }
}
